# Generated by Django 3.2.25 on 2026-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nav',
            old_name='is_site',
            new_name='is_http',
        ),
        migrations.AlterField(
            model_name='nav',
            name='position',
            field=models.SmallIntegerField(choices=[(0, '顶部导航'), (1, '脚部导航')], default=1, verbose_name='导航位置'),
        ),
    ]
